### ISSUE TITLE
get error with typescript 5

### ISSUE THREAD

**Issue by agrozyme** [tommy351/tsc-multi#19]
When I use typescript 5, I get the error in compiler mjs (cjs is ok):
Error: Debug Failure. Unhandled SyntaxKind: ImportClause.

This setting is ok when I use typescript 4 
(only get wran: DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.)

tsc-multi.json
```
{
  "targets": [
    { "extname": ".mjs", "module": "ESNext", "moduleResolution": "NodeNext" },
    { "extname": ".js", "module": "CommonJS", "moduleResolution": "Node" }
  ],
  "projects": ["."]
}

```

**Comment by tommy351** [comment]
I think the reason is the function signature changes of `ts.factory.createImportDeclaration` and `ts.factory.createExportDeclaration` in TypeScript 5.0. This issue will be fixed later.

Commit: https://github.com/tommy351/tsc-multi/pull/20/commits/20d7e26f82e36dbe9a58e2cb7a913b6191e73061

**Comment by tommy351** [comment]
`tsc-multi@1.0.0` released.
